"""baseline schema

Revision ID: 96f61a589162
Revises: 
Create Date: 2026-08-27 09:57:51.881088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f61a589162'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ailos_client_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('token_type', sa.String(length=40), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ailos_client_tokens_environment'), 'ailos_client_tokens', ['environment'], unique=True)
    op.create_table('ailos_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_convenio', sa.String(length=20), nullable=False),
    sa.Column('codigo_carteira', sa.Integer(), nullable=False),
    sa.Column('cooperativa_codigo', sa.String(length=20), nullable=True),
    sa.Column('conta_numero', sa.String(length=20), nullable=True),
    sa.Column('conta_digito', sa.String(length=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('cooperado_token_encrypted', sa.Text(), nullable=True),
    sa.Column('cooperado_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refresh_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('auto_relogin_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ailos_lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('ticket', sa.String(length=60), nullable=False),
    sa.Column('numero_convenio', sa.String(length=20), nullable=False),
    sa.Column('billing_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ailos_lotes_ticket'), 'ailos_lotes', ['ticket'], unique=True)
    op.create_table('ailos_retorno_arquivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_convenio', sa.String(length=20), nullable=False),
    sa.Column('data_movimento', sa.Date(), nullable=False),
    sa.Column('ticket', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('storage_object_key', sa.String(length=255), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('user_role', sa.String(length=30), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_method'), 'audit_logs', ['method'], unique=False)
    op.create_index(op.f('ix_audit_logs_path'), 'audit_logs', ['path'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_role'), 'audit_logs', ['user_role'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('trade_name', sa.String(length=180), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DELINQUENT', 'SUSPENDED', name='clientstatus'), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('extra_emails', sa.JSON(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('contacts', sa.JSON(), nullable=True),
    sa.Column('zip_code', sa.String(length=12), nullable=True),
    sa.Column('address_line', sa.String(length=180), nullable=True),
    sa.Column('address_number', sa.String(length=30), nullable=True),
    sa.Column('address_complement', sa.String(length=120), nullable=True),
    sa.Column('neighborhood', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('billing_day', sa.Integer(), nullable=True),
    sa.Column('rg_ie', sa.String(length=30), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('emergency_contacts', sa.JSON(), nullable=True),
    sa.Column('boleto_format', sa.String(length=20), nullable=True),
    sa.Column('boleto_fee', sa.String(length=3), nullable=True),
    sa.Column('issue_invoice', sa.String(length=3), nullable=True),
    sa.Column('tributacao', sa.String(length=30), nullable=True),
    sa.Column('iss_retido', sa.String(length=3), nullable=True),
    sa.Column('optante_simples', sa.String(length=3), nullable=True),
    sa.Column('delivery_method', sa.String(length=20), nullable=True),
    sa.Column('send_boleto_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_cpf_cnpj'), 'clients', ['cpf_cnpj'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('closure_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_month', sa.String(length=7), nullable=False),
    sa.Column('filter_type', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_closure_jobs_id'), 'closure_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_closure_jobs_status'), 'closure_jobs', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('review_status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'RESUBMISSION_REQUESTED', name='documentreviewstatus'), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_object_key'), 'documents', ['object_key'], unique=True)
    op.create_index(op.f('ix_documents_reference_id'), 'documents', ['reference_id'], unique=False)
    op.create_index(op.f('ix_documents_reference_type'), 'documents', ['reference_type'], unique=False)
    op.create_table('integration_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('batch_id', sa.String(length=40), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(length=80), nullable=False),
    sa.Column('transaction_id', sa.String(length=40), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('response_code', sa.String(length=20), nullable=True),
    sa.Column('response_description', sa.Text(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_logs_batch_id'), 'integration_logs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_integration_logs_entity_id'), 'integration_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_integration_logs_entity_type'), 'integration_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_integration_logs_id'), 'integration_logs', ['id'], unique=False)
    op.create_index(op.f('ix_integration_logs_operation'), 'integration_logs', ['operation'], unique=False)
    op.create_index(op.f('ix_integration_logs_provider'), 'integration_logs', ['provider'], unique=False)
    op.create_index(op.f('ix_integration_logs_response_code'), 'integration_logs', ['response_code'], unique=False)
    op.create_index(op.f('ix_integration_logs_success'), 'integration_logs', ['success'], unique=False)
    op.create_index(op.f('ix_integration_logs_transaction_id'), 'integration_logs', ['transaction_id'], unique=False)
    op.create_table('nfse_certificados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titular', sa.String(length=300), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('emissor', sa.String(length=300), nullable=True),
    sa.Column('valido_de', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valido_ate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=True),
    sa.Column('arquivo_cifrado', sa.LargeBinary(), nullable=False),
    sa.Column('senha_cifrada', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('enviado_por', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfse_certificados_ativo'), 'nfse_certificados', ['ativo'], unique=False)
    op.create_index(op.f('ix_nfse_certificados_cnpj'), 'nfse_certificados', ['cnpj'], unique=False)
    op.create_index(op.f('ix_nfse_certificados_id'), 'nfse_certificados', ['id'], unique=False)
    op.create_table('nfse_lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=20), nullable=False),
    sa.Column('competencia', sa.Date(), nullable=True),
    sa.Column('codigo_servico', sa.String(length=10), nullable=True),
    sa.Column('discriminacao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_notas', sa.Integer(), nullable=False),
    sa.Column('total_autorizadas', sa.Integer(), nullable=False),
    sa.Column('total_erro', sa.Integer(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('concluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfse_lotes_id'), 'nfse_lotes', ['id'], unique=False)
    op.create_index(op.f('ix_nfse_lotes_period_label'), 'nfse_lotes', ['period_label'], unique=False)
    op.create_index(op.f('ix_nfse_lotes_status'), 'nfse_lotes', ['status'], unique=False)
    op.create_table('payables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('supplier', sa.String(length=160), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payables_category'), 'payables', ['category'], unique=False)
    op.create_index(op.f('ix_payables_description'), 'payables', ['description'], unique=False)
    op.create_index(op.f('ix_payables_due_date'), 'payables', ['due_date'], unique=False)
    op.create_index(op.f('ix_payables_id'), 'payables', ['id'], unique=False)
    op.create_index(op.f('ix_payables_status'), 'payables', ['status'], unique=False)
    op.create_index(op.f('ix_payables_supplier'), 'payables', ['supplier'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('billing_interval_months', sa.Integer(), nullable=False),
    sa.Column('default_installation_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('default_uninstall_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('default_billing_day', sa.Integer(), nullable=True),
    sa.Column('default_duration_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_table('service_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('default_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('allow_installments', sa.Boolean(), nullable=False),
    sa.Column('remove_after_payment', sa.Boolean(), nullable=False),
    sa.Column('auto_add_on_uninstall', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_products_category'), 'service_products', ['category'], unique=False)
    op.create_index(op.f('ix_service_products_id'), 'service_products', ['id'], unique=False)
    op.create_index(op.f('ix_service_products_name'), 'service_products', ['name'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATIONAL', 'FINANCIAL', 'CLIENT', name='userrole'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('tokens_valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('sales_point', sa.String(length=120), nullable=True),
    sa.Column('seller_consultant', sa.String(length=120), nullable=True),
    sa.Column('vehicle_classification', sa.String(length=80), nullable=True),
    sa.Column('user_alert', sa.Text(), nullable=True),
    sa.Column('contract_number', sa.String(length=60), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('address_zip_code', sa.String(length=8), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('address_number', sa.String(length=30), nullable=True),
    sa.Column('address_complement', sa.String(length=120), nullable=True),
    sa.Column('neighborhood', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('plate', sa.String(length=10), nullable=False),
    sa.Column('chassis', sa.String(length=40), nullable=True),
    sa.Column('renavam', sa.String(length=20), nullable=True),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('manufacture_year', sa.Integer(), nullable=True),
    sa.Column('model_year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('fuel_type', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('fipe_code', sa.String(length=30), nullable=True),
    sa.Column('fipe_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING_VALIDATION', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CORRECTION_REQUESTED', 'ACTIVE', 'NO_TRACKER', 'REMOVED', 'BLOCKED', name='vehiclestatus'), nullable=False),
    sa.Column('uninstalled_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chassis')
    )
    op.create_index(op.f('ix_vehicles_client_id'), 'vehicles', ['client_id'], unique=False)
    op.create_index(op.f('ix_vehicles_contract_number'), 'vehicles', ['contract_number'], unique=False)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_plate'), 'vehicles', ['plate'], unique=True)
    op.create_index(op.f('ix_vehicles_renavam'), 'vehicles', ['renavam'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('trackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imei', sa.String(length=50), nullable=False),
    sa.Column('serial_number', sa.String(length=60), nullable=True),
    sa.Column('brand', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('status', sa.Enum('STOCK', 'INSTALLED', 'MAINTENANCE', 'LOST', 'DISCARDED', name='trackerstatus'), nullable=False),
    sa.Column('sim_number', sa.String(length=30), nullable=True),
    sa.Column('sim_iccid', sa.String(length=40), nullable=True),
    sa.Column('carrier', sa.String(length=30), nullable=True),
    sa.Column('sim_status', sa.String(length=30), nullable=True),
    sa.Column('firmware', sa.String(length=60), nullable=True),
    sa.Column('external_manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('external_manufacturer_label', sa.String(length=120), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('install_location', sa.String(length=120), nullable=True),
    sa.Column('chip_type', sa.Integer(), nullable=True),
    sa.Column('equipment_type', sa.Integer(), nullable=True),
    sa.Column('communication_type', sa.Integer(), nullable=True),
    sa.Column('service_plan_name', sa.String(length=120), nullable=True),
    sa.Column('installation_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('uninstall_date', sa.Date(), nullable=True),
    sa.Column('warranty_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('integration_status', sa.String(length=30), nullable=True),
    sa.Column('integration_last_code', sa.String(length=20), nullable=True),
    sa.Column('integration_last_description', sa.Text(), nullable=True),
    sa.Column('integration_last_transaction_id', sa.String(length=40), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trackers_client_id'), 'trackers', ['client_id'], unique=False)
    op.create_index(op.f('ix_trackers_external_manufacturer_id'), 'trackers', ['external_manufacturer_id'], unique=False)
    op.create_index(op.f('ix_trackers_id'), 'trackers', ['id'], unique=False)
    op.create_index(op.f('ix_trackers_imei'), 'trackers', ['imei'], unique=True)
    op.create_index(op.f('ix_trackers_integration_status'), 'trackers', ['integration_status'], unique=False)
    op.create_index(op.f('ix_trackers_serial_number'), 'trackers', ['serial_number'], unique=False)
    op.create_index(op.f('ix_trackers_vehicle_id'), 'trackers', ['vehicle_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('interveniente_client_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('tracker_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('billing_day', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=40), nullable=True),
    sa.Column('billing_modality', sa.String(length=20), nullable=False),
    sa.Column('bank', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('installation_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('uninstall_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('signed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('signed_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['interveniente_client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_client_id'), 'contracts', ['client_id'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_index(op.f('ix_contracts_interveniente_client_id'), 'contracts', ['interveniente_client_id'], unique=False)
    op.create_index(op.f('ix_contracts_plan_id'), 'contracts', ['plan_id'], unique=False)
    op.create_index(op.f('ix_contracts_tracker_id'), 'contracts', ['tracker_id'], unique=False)
    op.create_index(op.f('ix_contracts_vehicle_id'), 'contracts', ['vehicle_id'], unique=False)
    op.create_table('multiportal_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('batch_id', sa.String(length=40), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multiportal_outbox_batch_id'), 'multiportal_outbox', ['batch_id'], unique=False)
    op.create_index(op.f('ix_multiportal_outbox_id'), 'multiportal_outbox', ['id'], unique=False)
    op.create_index(op.f('ix_multiportal_outbox_next_attempt_at'), 'multiportal_outbox', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_multiportal_outbox_operation'), 'multiportal_outbox', ['operation'], unique=False)
    op.create_index(op.f('ix_multiportal_outbox_status'), 'multiportal_outbox', ['status'], unique=False)
    op.create_index(op.f('ix_multiportal_outbox_tracker_id'), 'multiportal_outbox', ['tracker_id'], unique=False)
    op.create_table('service_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('type', sa.Enum('INSTALL', 'MAINTENANCE', 'REMOVAL', 'TECH_VISIT', name='ordertype'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', name='orderstatus'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('tracker_id', sa.Integer(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_orders_id'), 'service_orders', ['id'], unique=False)
    op.create_index(op.f('ix_service_orders_number'), 'service_orders', ['number'], unique=True)
    op.create_table('tracker_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('previous_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('new_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('previous_client_id', sa.Integer(), nullable=True),
    sa.Column('new_client_id', sa.Integer(), nullable=True),
    sa.Column('previous_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracker_histories_action'), 'tracker_histories', ['action'], unique=False)
    op.create_index(op.f('ix_tracker_histories_id'), 'tracker_histories', ['id'], unique=False)
    op.create_index(op.f('ix_tracker_histories_tracker_id'), 'tracker_histories', ['tracker_id'], unique=False)
    op.create_table('client_charge_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('tracker_id', sa.Integer(), nullable=True),
    sa.Column('service_product_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('installment_count', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('remove_after_payment', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['service_product_id'], ['service_products.id'], ),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_charge_items_active'), 'client_charge_items', ['active'], unique=False)
    op.create_index(op.f('ix_client_charge_items_client_id'), 'client_charge_items', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_charge_items_contract_id'), 'client_charge_items', ['contract_id'], unique=False)
    op.create_index(op.f('ix_client_charge_items_id'), 'client_charge_items', ['id'], unique=False)
    op.create_index(op.f('ix_client_charge_items_service_product_id'), 'client_charge_items', ['service_product_id'], unique=False)
    op.create_index(op.f('ix_client_charge_items_status'), 'client_charge_items', ['status'], unique=False)
    op.create_index(op.f('ix_client_charge_items_title'), 'client_charge_items', ['title'], unique=False)
    op.create_index(op.f('ix_client_charge_items_tracker_id'), 'client_charge_items', ['tracker_id'], unique=False)
    op.create_index(op.f('ix_client_charge_items_vehicle_id'), 'client_charge_items', ['vehicle_id'], unique=False)
    op.create_table('service_order_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_order_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', name='orderstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', name='orderstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_order_status_logs_changed_by_id'), 'service_order_status_logs', ['changed_by_id'], unique=False)
    op.create_index(op.f('ix_service_order_status_logs_id'), 'service_order_status_logs', ['id'], unique=False)
    op.create_index(op.f('ix_service_order_status_logs_service_order_id'), 'service_order_status_logs', ['service_order_id'], unique=False)
    op.create_table('billings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('payer_client_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('tracker_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('billing_type', sa.String(length=30), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=True),
    sa.Column('installment_total', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'OVERDUE', 'CANCELED', name='billingstatus'), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('receipt_number', sa.String(length=40), nullable=True),
    sa.Column('period_label', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['client_charge_items.id'], ),
    sa.ForeignKeyConstraint(['payer_client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billings_billing_type'), 'billings', ['billing_type'], unique=False)
    op.create_index(op.f('ix_billings_client_id'), 'billings', ['client_id'], unique=False)
    op.create_index(op.f('ix_billings_contract_id'), 'billings', ['contract_id'], unique=False)
    op.create_index(op.f('ix_billings_due_date'), 'billings', ['due_date'], unique=False)
    op.create_index(op.f('ix_billings_id'), 'billings', ['id'], unique=False)
    op.create_index(op.f('ix_billings_item_id'), 'billings', ['item_id'], unique=False)
    op.create_index(op.f('ix_billings_payer_client_id'), 'billings', ['payer_client_id'], unique=False)
    op.create_index(op.f('ix_billings_period_label'), 'billings', ['period_label'], unique=False)
    op.create_index(op.f('ix_billings_receipt_number'), 'billings', ['receipt_number'], unique=False)
    op.create_index(op.f('ix_billings_status'), 'billings', ['status'], unique=False)
    op.create_index(op.f('ix_billings_title'), 'billings', ['title'], unique=False)
    op.create_index(op.f('ix_billings_tracker_id'), 'billings', ['tracker_id'], unique=False)
    op.create_index(op.f('ix_billings_vehicle_id'), 'billings', ['vehicle_id'], unique=False)
    op.create_table('ailos_api_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=40), nullable=True),
    sa.Column('billing_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_id'], ['billings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ailos_boletos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('numero_convenio', sa.String(length=20), nullable=False),
    sa.Column('numero_documento', sa.String(length=40), nullable=True),
    sa.Column('nosso_numero', sa.String(length=40), nullable=True),
    sa.Column('identificador_unico_titulo', sa.String(length=60), nullable=True),
    sa.Column('linha_digitavel', sa.String(length=60), nullable=True),
    sa.Column('codigo_barras', sa.String(length=60), nullable=True),
    sa.Column('valor_nominal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('status_ailos', sa.String(length=40), nullable=True),
    sa.Column('pix_emv', sa.Text(), nullable=True),
    sa.Column('pix_qr_base64', sa.Text(), nullable=True),
    sa.Column('payload_request', sa.JSON(), nullable=True),
    sa.Column('payload_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_id'], ['billings.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['ailos_lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ailos_boletos_billing_id'), 'ailos_boletos', ['billing_id'], unique=True)
    op.create_table('billing_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=40), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_id'], ['billings.id'], ),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_change_logs_billing_id'), 'billing_change_logs', ['billing_id'], unique=False)
    op.create_index(op.f('ix_billing_change_logs_changed_by_user_id'), 'billing_change_logs', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_billing_change_logs_field_name'), 'billing_change_logs', ['field_name'], unique=False)
    op.create_index(op.f('ix_billing_change_logs_id'), 'billing_change_logs', ['id'], unique=False)
    op.create_table('billing_charge_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_id'], ['billings.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['client_charge_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_id', 'item_id', name='uq_billing_charge_item')
    )
    op.create_index(op.f('ix_billing_charge_items_billing_id'), 'billing_charge_items', ['billing_id'], unique=False)
    op.create_index(op.f('ix_billing_charge_items_id'), 'billing_charge_items', ['id'], unique=False)
    op.create_index(op.f('ix_billing_charge_items_item_id'), 'billing_charge_items', ['item_id'], unique=False)
    op.create_table('nfse_notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('numero_rps', sa.String(length=15), nullable=True),
    sa.Column('serie_rps', sa.String(length=5), nullable=True),
    sa.Column('numero_lote', sa.String(length=20), nullable=True),
    sa.Column('protocolo', sa.String(length=60), nullable=True),
    sa.Column('situacao', sa.String(length=2), nullable=True),
    sa.Column('numero_nfse', sa.String(length=20), nullable=True),
    sa.Column('serie_nfse', sa.String(length=5), nullable=True),
    sa.Column('codigo_verificacao', sa.String(length=20), nullable=True),
    sa.Column('chave_acesso', sa.String(length=60), nullable=True),
    sa.Column('link_visualizacao', sa.Text(), nullable=True),
    sa.Column('data_emissao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('erro_codigo', sa.String(length=10), nullable=True),
    sa.Column('erro_mensagem', sa.Text(), nullable=True),
    sa.Column('xml_envio', sa.Text(), nullable=True),
    sa.Column('xml_retorno', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_id'], ['billings.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['nfse_lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfse_notas_billing_id'), 'nfse_notas', ['billing_id'], unique=True)
    op.create_index(op.f('ix_nfse_notas_lote_id'), 'nfse_notas', ['lote_id'], unique=False)
    op.create_index(op.f('ix_nfse_notas_numero_nfse'), 'nfse_notas', ['numero_nfse'], unique=False)
    op.create_index(op.f('ix_nfse_notas_protocolo'), 'nfse_notas', ['protocolo'], unique=False)
    op.create_index(op.f('ix_nfse_notas_status'), 'nfse_notas', ['status'], unique=False)
    op.create_table('uninstall_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('payer_client_id', sa.Integer(), nullable=True),
    sa.Column('uninstall_date', sa.Date(), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('service_product_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_id'], ['billings.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['payer_client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['service_product_id'], ['service_products.id'], ),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uninstall_events_client_id'), 'uninstall_events', ['client_id'], unique=False)
    op.create_index(op.f('ix_uninstall_events_id'), 'uninstall_events', ['id'], unique=False)
    op.create_index(op.f('ix_uninstall_events_payer_client_id'), 'uninstall_events', ['payer_client_id'], unique=False)
    op.create_index(op.f('ix_uninstall_events_status'), 'uninstall_events', ['status'], unique=False)
    op.create_index(op.f('ix_uninstall_events_tracker_id'), 'uninstall_events', ['tracker_id'], unique=False)
    op.create_index(op.f('ix_uninstall_events_uninstall_date'), 'uninstall_events', ['uninstall_date'], unique=False)
    op.create_index(op.f('ix_uninstall_events_vehicle_id'), 'uninstall_events', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uninstall_events_vehicle_id'), table_name='uninstall_events')
    op.drop_index(op.f('ix_uninstall_events_uninstall_date'), table_name='uninstall_events')
    op.drop_index(op.f('ix_uninstall_events_tracker_id'), table_name='uninstall_events')
    op.drop_index(op.f('ix_uninstall_events_status'), table_name='uninstall_events')
    op.drop_index(op.f('ix_uninstall_events_payer_client_id'), table_name='uninstall_events')
    op.drop_index(op.f('ix_uninstall_events_id'), table_name='uninstall_events')
    op.drop_index(op.f('ix_uninstall_events_client_id'), table_name='uninstall_events')
    op.drop_table('uninstall_events')
    op.drop_index(op.f('ix_nfse_notas_status'), table_name='nfse_notas')
    op.drop_index(op.f('ix_nfse_notas_protocolo'), table_name='nfse_notas')
    op.drop_index(op.f('ix_nfse_notas_numero_nfse'), table_name='nfse_notas')
    op.drop_index(op.f('ix_nfse_notas_lote_id'), table_name='nfse_notas')
    op.drop_index(op.f('ix_nfse_notas_billing_id'), table_name='nfse_notas')
    op.drop_table('nfse_notas')
    op.drop_index(op.f('ix_billing_charge_items_item_id'), table_name='billing_charge_items')
    op.drop_index(op.f('ix_billing_charge_items_id'), table_name='billing_charge_items')
    op.drop_index(op.f('ix_billing_charge_items_billing_id'), table_name='billing_charge_items')
    op.drop_table('billing_charge_items')
    op.drop_index(op.f('ix_billing_change_logs_id'), table_name='billing_change_logs')
    op.drop_index(op.f('ix_billing_change_logs_field_name'), table_name='billing_change_logs')
    op.drop_index(op.f('ix_billing_change_logs_changed_by_user_id'), table_name='billing_change_logs')
    op.drop_index(op.f('ix_billing_change_logs_billing_id'), table_name='billing_change_logs')
    op.drop_table('billing_change_logs')
    op.drop_index(op.f('ix_ailos_boletos_billing_id'), table_name='ailos_boletos')
    op.drop_table('ailos_boletos')
    op.drop_table('ailos_api_logs')
    op.drop_index(op.f('ix_billings_vehicle_id'), table_name='billings')
    op.drop_index(op.f('ix_billings_tracker_id'), table_name='billings')
    op.drop_index(op.f('ix_billings_title'), table_name='billings')
    op.drop_index(op.f('ix_billings_status'), table_name='billings')
    op.drop_index(op.f('ix_billings_receipt_number'), table_name='billings')
    op.drop_index(op.f('ix_billings_period_label'), table_name='billings')
    op.drop_index(op.f('ix_billings_payer_client_id'), table_name='billings')
    op.drop_index(op.f('ix_billings_item_id'), table_name='billings')
    op.drop_index(op.f('ix_billings_id'), table_name='billings')
    op.drop_index(op.f('ix_billings_due_date'), table_name='billings')
    op.drop_index(op.f('ix_billings_contract_id'), table_name='billings')
    op.drop_index(op.f('ix_billings_client_id'), table_name='billings')
    op.drop_index(op.f('ix_billings_billing_type'), table_name='billings')
    op.drop_table('billings')
    op.drop_index(op.f('ix_service_order_status_logs_service_order_id'), table_name='service_order_status_logs')
    op.drop_index(op.f('ix_service_order_status_logs_id'), table_name='service_order_status_logs')
    op.drop_index(op.f('ix_service_order_status_logs_changed_by_id'), table_name='service_order_status_logs')
    op.drop_table('service_order_status_logs')
    op.drop_index(op.f('ix_client_charge_items_vehicle_id'), table_name='client_charge_items')
    op.drop_index(op.f('ix_client_charge_items_tracker_id'), table_name='client_charge_items')
    op.drop_index(op.f('ix_client_charge_items_title'), table_name='client_charge_items')
    op.drop_index(op.f('ix_client_charge_items_status'), table_name='client_charge_items')
    op.drop_index(op.f('ix_client_charge_items_service_product_id'), table_name='client_charge_items')
    op.drop_index(op.f('ix_client_charge_items_id'), table_name='client_charge_items')
    op.drop_index(op.f('ix_client_charge_items_contract_id'), table_name='client_charge_items')
    op.drop_index(op.f('ix_client_charge_items_client_id'), table_name='client_charge_items')
    op.drop_index(op.f('ix_client_charge_items_active'), table_name='client_charge_items')
    op.drop_table('client_charge_items')
    op.drop_index(op.f('ix_tracker_histories_tracker_id'), table_name='tracker_histories')
    op.drop_index(op.f('ix_tracker_histories_id'), table_name='tracker_histories')
    op.drop_index(op.f('ix_tracker_histories_action'), table_name='tracker_histories')
    op.drop_table('tracker_histories')
    op.drop_index(op.f('ix_service_orders_number'), table_name='service_orders')
    op.drop_index(op.f('ix_service_orders_id'), table_name='service_orders')
    op.drop_table('service_orders')
    op.drop_index(op.f('ix_multiportal_outbox_tracker_id'), table_name='multiportal_outbox')
    op.drop_index(op.f('ix_multiportal_outbox_status'), table_name='multiportal_outbox')
    op.drop_index(op.f('ix_multiportal_outbox_operation'), table_name='multiportal_outbox')
    op.drop_index(op.f('ix_multiportal_outbox_next_attempt_at'), table_name='multiportal_outbox')
    op.drop_index(op.f('ix_multiportal_outbox_id'), table_name='multiportal_outbox')
    op.drop_index(op.f('ix_multiportal_outbox_batch_id'), table_name='multiportal_outbox')
    op.drop_table('multiportal_outbox')
    op.drop_index(op.f('ix_contracts_vehicle_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_tracker_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_plan_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_interveniente_client_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_client_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_trackers_vehicle_id'), table_name='trackers')
    op.drop_index(op.f('ix_trackers_serial_number'), table_name='trackers')
    op.drop_index(op.f('ix_trackers_integration_status'), table_name='trackers')
    op.drop_index(op.f('ix_trackers_imei'), table_name='trackers')
    op.drop_index(op.f('ix_trackers_id'), table_name='trackers')
    op.drop_index(op.f('ix_trackers_external_manufacturer_id'), table_name='trackers')
    op.drop_index(op.f('ix_trackers_client_id'), table_name='trackers')
    op.drop_table('trackers')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_vehicles_renavam'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_contract_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_client_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_service_products_name'), table_name='service_products')
    op.drop_index(op.f('ix_service_products_id'), table_name='service_products')
    op.drop_index(op.f('ix_service_products_category'), table_name='service_products')
    op.drop_table('service_products')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_payables_supplier'), table_name='payables')
    op.drop_index(op.f('ix_payables_status'), table_name='payables')
    op.drop_index(op.f('ix_payables_id'), table_name='payables')
    op.drop_index(op.f('ix_payables_due_date'), table_name='payables')
    op.drop_index(op.f('ix_payables_description'), table_name='payables')
    op.drop_index(op.f('ix_payables_category'), table_name='payables')
    op.drop_table('payables')
    op.drop_index(op.f('ix_nfse_lotes_status'), table_name='nfse_lotes')
    op.drop_index(op.f('ix_nfse_lotes_period_label'), table_name='nfse_lotes')
    op.drop_index(op.f('ix_nfse_lotes_id'), table_name='nfse_lotes')
    op.drop_table('nfse_lotes')
    op.drop_index(op.f('ix_nfse_certificados_id'), table_name='nfse_certificados')
    op.drop_index(op.f('ix_nfse_certificados_cnpj'), table_name='nfse_certificados')
    op.drop_index(op.f('ix_nfse_certificados_ativo'), table_name='nfse_certificados')
    op.drop_table('nfse_certificados')
    op.drop_index(op.f('ix_integration_logs_transaction_id'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_success'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_response_code'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_provider'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_operation'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_id'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_entity_type'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_entity_id'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_batch_id'), table_name='integration_logs')
    op.drop_table('integration_logs')
    op.drop_index(op.f('ix_documents_reference_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_reference_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_object_key'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_closure_jobs_status'), table_name='closure_jobs')
    op.drop_index(op.f('ix_closure_jobs_id'), table_name='closure_jobs')
    op.drop_table('closure_jobs')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_cpf_cnpj'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_audit_logs_user_role'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_path'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_method'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('ailos_retorno_arquivos')
    op.drop_index(op.f('ix_ailos_lotes_ticket'), table_name='ailos_lotes')
    op.drop_table('ailos_lotes')
    op.drop_table('ailos_integrations')
    op.drop_index(op.f('ix_ailos_client_tokens_environment'), table_name='ailos_client_tokens')
    op.drop_table('ailos_client_tokens')
    # ### end Alembic commands ###
